### ISSUE TITLE
Convert Docker image to Singularity image

### ISSUE THREAD

**Issue by julianpistorius** [breakfast-carpentry/menu-suggestions#1]
Somebody asked me:

> How can we convert a Docker image to a Singularity image? Yesterday we had a local image for Diamond, but it is a Docker image. 
> 
> I tried to follow the instruction in https://github.com/singularityware/docker2singularity 
> But for some reason, I converted the Docker image to an `.img` file, instead of the `.simg` file, and when I tried to run that `.img` file, it does not work.

**Comment by Yingru** [comment]
Figured it out! Thank @julianpistorius  for helping! :)
so the following command: 
`docker run \                                                                   
-v /var/run/docker.sock:/var/run/docker.sock \                       # ship the docker in the host to the container
-v D:\host\path\where\to\output\singularity\image:/output \   # link the host-path with container output
--privileged -t --rm \                                                                # some extra options for docker
singularityware/docker2singularity \                                       # an image that perform the d2s convert
ubuntu:14.04`                                                                         # the actually docker image want to convert

one tip is for the docker image you'd like to convert, it should have enough information to identify itself.
run:
`docker images` 
and include the name of the image as well as its tag. (such as 14.04 for the example case).

**Comment by mofarehghazwani** [comment]
I converted .ova to  vmdk  image format ,then to .img using quem-img tool. my goal is to convert this to singularity .img.
Do I have to convert the .img that I got from quem-img to docker image, then to singularity image, or this .img is okey?

**Comment by julianpistorius** [comment]
Hi @mofarehghazwani. I didn't think this is possible, it seems you can do it! 

It looks like you can go from VMDK directly to a Docker image:

https://blog.inslash.com/how-to-convert-vmdk-to-a-docker-image-be939745ed8a

Then you can use the above technique to go from this Docker image to a Singularity image.

Let us know if you manage to get this working!
